fix mfcobol-errformat2-copybook-netx-sx matcher
spgennard/vscode_cobol pull request #221
Opened 2020-10-14 06:45 UTC by GitMensch

previously was identical to mfcobol-errformat2-netx-sx, missed the separator comma

2020-10-14 15:49 UTC, spgennard requested changes
The unit tests fail, as I thought the regex looks wrong:

```shell
  1) Issues Raised Test Suite
       Issue: Package.json checks:
     AssertionError [ERR_ASSERTION]: 2/[object Object] : SyntaxError: Invalid regular expression: /^\*+\s+(COBCH\d+)([USEWI])\s+([^:]+):[^,]++(.*)\((\d+),(\d+).*\).*$/: Nothing to repeat
  	at Context.<anonymous> (out/test/suite/issues.test.js:136:28)
  	at processImmediate (internal/timers.js:439:21)

```

2020-10-15 06:57 UTC, GitMensch commented
Can you automate the tests so that they are automatically done for each PR vi CI?

2020-10-15 07:15 UTC, GitMensch commented
Fixed the typo, should have been a `,` instead of a `+`.

2020-10-15 07:24 UTC, spgennard commented
> Can you automate the tests so that they are automatically done for each PR vi CI?

The tests are GUI, so I would need a dedicated VM, so sorry not at the moment.

2020-10-15 07:35 UTC, GitMensch commented
> > Can you automate the tests so that they are automatically done for each PR vi CI?
> 
> The tests are GUI, so I would need a dedicated VM, so sorry not at the moment.

I see. I've thought that these would be plain `npm`, it may be useful to split the tests to be able to automate every non-gui part.

2020-10-15 07:46 UTC, spgennard commented
> > > Can you automate the tests so that they are automatically done for each PR vi CI?
> > 
> > 
> > The tests are GUI, so I would need a dedicated VM, so sorry not at the moment.
> 
> I see. I've thought that these would be plain `npm`, it may be useful to split the tests to be able to automate every non-gui part.

All of the tests have a dependency on the vscode package & the initialization of the extension.

These tests pickup the problem matchers from the package.json via the extension, so vscode has to load & the extension setup, then it can find the matchers & the regex's to test.

2020-10-15 07:55 UTC, GitMensch commented
> All of the tests have a dependency on the vscode package & the initialization of the extension.
>
> These tests pickup the problem matchers from the package.json via the extension, so vscode has to load & the extension setup, then it can find the matchers & the regex's to test.

I see. I try to look later how other extensions do this (I guess there's some boiler plate that may be used).

For now, I'd like to keep this PR about this PR and otherwise am interested to see the GC-patterns be [adjusted](https://github.com/spgennard/vscode_cobol/issues/198#issuecomment-708198820).

2020-10-16 23:18 UTC, GitMensch commented
Is there anything "open" in your view for this PR?

2020-10-18 14:37 UTC, GitMensch commented
Included in 764f3cae67ea7a6b83467415fb883adaa8119f2f.

2020-10-18 14:37 UTC, closed without merging